-- Create the knowledge_base table
CREATE TABLE knowledge_base (
    id TEXT PRIMARY KEY,
    category TEXT,
    content TEXT
);

-- Populate the table with initial data
INSERT INTO knowledge_base (id, category, content) VALUES
('visa_uk_1', 'visa', 'UK student visa: General Tier 4 application, cost £363 (approx. ₦544,500), requires passport, TB test, proof of funds.'),
('essay_structure_1', 'essay', 'Standard essay structure: Introduction (hook, thesis statement, approx. 10-15% of word count), Body Paragraphs (topic sentence, evidence, explanation, transition, approx. 70-80%), Conclusion (summary, restate thesis, final thought, approx. 10-15%).'),
('program_canada_cs_1', 'program_info', 'Computer Science in Canada: Many universities offer co-op programs. Check specific university requirements for English proficiency (IELTS/TOEFL) and academic prerequisites.'),
('scholarship_usa_general_1', 'scholarship', 'USA Scholarships: Look for university-specific scholarships, as well as external ones like Fulbright. Deadlines vary greatly, start searching early.'),
('visa_schengen_1', 'visa', 'Schengen Area student visa: Allows study in many European countries. Requirements typically include acceptance letter, proof of funds, health insurance. Processing times can be long.'),
('program_uk_mba_1', 'program_info', 'UK MBA Programs: Often 1 year in duration. Look for AMBA, AACSB, or EQUIS accreditations. Work experience is usually required.'),
('essay_plagiarism_1', 'essay', 'Plagiarism: Always cite your sources. Use tools like Turnitin if available. Understand paraphrasing vs. direct quoting.'),
('visa_usa_f1_1', 'visa', 'USA F-1 Visa: For students attending academic programs. Requires SEVIS I-20 form from the university. Interview is a key part.'),
('scholarship_canada_general_1', 'scholarship', 'Canada Scholarships: Explore Vanier Canada Graduate Scholarships (doctoral) and university-specific awards. Check eligibility carefully.'),
('program_australia_eng_1', 'program_info', 'Engineering in Australia: Engineers Australia accreditation is important. Many specializations available. Consider cost of living.'),
('visa_australia_1', 'visa', 'Australia Student Visa (subclass 500): Apply online. Requires Confirmation of Enrolment (CoE), proof of funds, health insurance (OSHC).'),
('essay_referencing_1', 'essay', 'Referencing Styles: Common styles include APA, MLA, Harvard, Chicago. Check your department’s preference. Consistency is key.'),
('program_germany_tuition_1', 'program_info', 'Germany Public Universities: Many offer tuition-free education to international students (for Bachelor''s and Master''s). Semester contribution fee applies.'),
('scholarship_uk_chevening_1', 'scholarship', 'UK Chevening Scholarships: Highly competitive, for Master''s degrees. Covers tuition, living expenses, travel. Requires leadership potential.'),
('visa_canada_sds_1', 'visa', 'Canada Student Direct Stream (SDS): For faster visa processing from certain countries. Requires GIC of CAD 10,000, tuition payment for first year, IELTS 6.0 in all bands.'),
('essay_thesis_statement_1', 'essay', 'Thesis Statement: A clear, concise statement of your main argument. Usually at the end of the introduction. Guides your essay.'),
('program_netherlands_eng_1', 'program_info', 'English-Taught Programs in Netherlands: Wide range available, especially at Master''s level. Known for international environment.'),
('scholarship_daad_germany_1', 'scholarship', 'DAAD Scholarships (Germany): Offers various scholarships for international students for different academic levels. Check specific program requirements.'),
('visa_ireland_1', 'visa', 'Ireland Study Visa: Apply online. Proof of funds is crucial. May need to register with Garda National Immigration Bureau (GNIB) after arrival.'),
('essay_proofreading_1', 'essay', 'Proofreading: Essential step before submission. Check for grammar, spelling, punctuation errors. Read aloud or ask a friend to review.'),
('program_usa_masters_gre_1', 'program_info', 'USA Master''s Programs: GRE (Graduate Record Examinations) often required, especially for STEM and some arts/humanities. Check university/program specifics.'),
('scholarship_erasmus_mundus_1', 'scholarship', 'Erasmus Mundus Joint Masters Scholarships: EU-funded, for Master''s programs in multiple European countries. Highly prestigious.'),
('visa_france_vls_ts_1', 'visa', 'France Long-Stay Visa (VLS-TS "étudiant"): Acts as residence permit for the first year. Requires Campus France procedure for many nationalities.'),
('essay_topic_selection_1', 'essay', 'Essay Topic Selection: Choose something you are interested in and that fits the assignment prompt. Brainstorm and narrow down options.'),
('program_online_mba_1', 'program_info', 'Online MBA Programs: Offers flexibility. Check accreditation (e.g., AACSB, AMBA, EQUIS). Consider networking opportunities.'),
('scholarship_australia_awards_1', 'scholarship', 'Australia Awards Scholarships: For students from developing countries. Covers full tuition, travel, living expenses. Focus on development impact.'),
('visa_new_zealand_1', 'visa', 'New Zealand Student Visa: Apply online. Need offer of place, proof of funds, and good health/character. Post-study work options available.'),
('essay_critical_thinking_1', 'essay', 'Critical Thinking in Essays: Go beyond description. Analyze, evaluate, synthesize information. Develop your own argument.'),
('program_switzerland_hospitality_1', 'program_info', 'Hospitality Management in Switzerland: World-renowned programs. Often include internships. High tuition fees but strong career prospects.'),
('scholarship_commonwealth_1', 'scholarship', 'Commonwealth Scholarships: For Master''s and PhD study in Commonwealth countries. For citizens of eligible Commonwealth countries.'),
('visa_japan_1', 'visa', 'Japan Student Visa: Requires Certificate of Eligibility (CoE) from Japanese immigration, obtained via your host institution.'),
('essay_conclusion_1', 'essay', 'Essay Conclusion: Summarize main points, restate thesis in different words, offer a final thought or implication. Don''t introduce new information.'),
('program_singapore_asia_1', 'program_info', 'Study in Singapore: Hub for education in Asia. NUS and NTU are top-ranked universities. High cost of living but safe and modern.'),
('scholarship_partial_funding_1', 'scholarship', 'Partial Scholarships: Don''t overlook smaller awards. Multiple partial scholarships can add up. Check local organizations and university departments.'),
('visa_south_korea_d2_1', 'visa', 'South Korea D-2 Visa: For students enrolled in regular academic programs. Requires admission letter, proof of funds, etc.'),
('essay_research_question_1', 'essay', 'Research Question: A clear, focused question that your research aims to answer. Important for research papers and dissertations.'),
('program_uk_law_llm_1', 'program_info', 'UK LLM (Master of Laws): Many specializations available (e.g., commercial, human rights). Can be 1 year full-time.'),
('scholarship_university_specific_1', 'scholarship', 'University-Specific Scholarships: Most universities offer scholarships for international students. Check their financial aid / international office website.'),
('visa_spain_1', 'visa', 'Spain Student Visa: Requires proof of funds, medical insurance, acceptance letter. Apply at Spanish consulate in your country.'),
('essay_annotated_bibliography_1', 'essay', 'Annotated Bibliography: A list of citations followed by a brief summary and evaluation (annotation) of each source. Shows research depth.'),
('program_usa_phd_funding_1', 'program_info', 'USA PhD Programs: Often fully funded (tuition waiver + stipend) through research or teaching assistantships, especially in STEM.'),
('scholarship_application_tips_1', 'scholarship', 'Scholarship Application Tips: Start early, read eligibility carefully, tailor your application, get strong recommendation letters, proofread everything.'),
('visa_italy_1', 'visa', 'Italy Student Visa (Type D): Requires pre-enrollment at university, proof of accommodation and financial means.'),
('essay_literature_review_1', 'essay', 'Literature Review: A survey of scholarly sources on a specific topic. Provides an overview of current knowledge, allowing you to identify relevant theories, methods, and gaps.'),
('program_canada_college_diploma_1', 'program_info', 'Canadian College Diplomas/Certificates: Offer practical, career-focused education. Often shorter and cheaper than degrees. Can be a pathway to PR.'),
('scholarship_essay_writing_1', 'scholarship', 'Scholarship Essay Writing: Focus on the prompt, showcase your personality and achievements, be genuine and compelling. Tell a story.'),
('visa_china_x1_x2_1', 'visa', 'China Student Visa: X1 for long-term (>180 days), X2 for short-term. Requires JW201 or JW202 form and admission notice.'),
('essay_avoid_generalizations_1', 'essay', 'Avoid Generalizations in Essays: Be specific, provide evidence. Avoid vague statements or unsupported claims. Use precise language.'),
('program_ireland_tech_1', 'program_info', 'Ireland Tech Sector: Growing rapidly (''Silicon Docks''). Many tech companies have European HQs there. Good post-study work opportunities for IT grads.'),
('scholarship_fulbright_foreign_student_1', 'scholarship', 'Fulbright Foreign Student Program (USA): Prestigious scholarship for graduate study and research in the US. Highly competitive, country-specific application process.');
